### ISSUE TITLE
Missing strings for some texts

### ISSUE THREAD

**Issue by piotr-kwiatkowski** [ay8s/alpenglow-localization#1]
I'm currently preparing Polish translation and I believe there are missing strings for the following texts:

1. "_Alpenglow never stores your location..._"
2. "_In some cases iOS may not wake Alpenglow..._"

It is visible at the bottom of "You're Awesome!" section:
![missing-texts](https://user-images.githubusercontent.com/7272022/87930174-e59eb280-ca87-11ea-913e-9c33aaf1efef.png)

**Comment by ay8s** [comment]
@piotr-kwiatkowski Thanks for mentioning those. I'll get those added to the file and merged in tomorrow. 

Excited to get Polish added in 👍  Thanks for helping out.

**Comment by ay8s** [comment]
Hey @piotr-kwiatkowski.

I have replaced the file with a new one ready for version 6 of the app. It includes files for French, German and Spanish. I'd still love to add in Polish.

The file should be more complete now with those missing strings also added. 👍
